# Generated by Django 4.2.3 on 2023-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_alter_cars_dropoff_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cars",
            name="booked_by",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
